export default {
  index: 'Overview',
  'docker-quickstart': 'Docker Quick Start',
  'tenant-seed-setup': 'Initial Account Setup',
  'external-services': 'Choosing Your External Services',
  'importing-transactions': 'Importing Transactions',
  'investment-portfolios': 'Investment Portfolios',
  'passive-income': 'Passive Income',
  'plaid-bank-sync': 'Bank Sync with Plaid',
  'ai-classification': 'AI Classification',
  'choosing-categories': 'Choosing the Right Category',
  'tracking-subscriptions': 'Tracking Subscriptions',
  'financial-insights': 'Financial Insights',
  'connecting-ai-agents': 'Connecting AI Agents & Other Systems',
  'using-bliss-with-claude-mcp': 'Use Bliss with Claude (MCP)',
  'mcp-tool-reference': 'MCP Tool Reference',
  'multi-tenant-deployment': 'Multi-Tenant Deployment',
  maintenance: 'Maintenance',
  'processing-status': 'Why Are My Numbers Updating?',
  'key-rotation': 'Key Rotation',
};
