module.exports = {
  name: 'DIVIDEND_OPPORTUNITY',
  rubric: `DIVIDEND_OPPORTUNITY
Focus: dividend income generated by stock holdings, plus broader passive income (rent, interest) when available.
DENOMINATOR DISCIPLINE — this is the single most common mistake on this lens. Yield is computed against the value of dividend-paying stocks, NOT the total portfolio. Use \`weightedDividendYieldPct\` from the pre-computed signals (already weighted across dividend-paying holdings only). Never divide annualized dividends by total portfolio value to express a "yield" — that's misleading because real estate, debt, cash, and non-dividend stocks aren't dividend-generating.
When the user has a "Passive Income" category in their financial summary, KEY SIGNALS includes the last-90-days actuals from that category. Anchor the insight to the actual income posted (\`passiveIncomeRecent\`) when available — it's more credible than projections from yields. Frame projections as "trailing yield implies …" only when actuals aren't yet available.
Severity:
- INFO (default): describe dividends received recently, plus current annualized projection from yields.
- POSITIVE: dividend income grew ≥10% YoY from existing holdings (organic growth, not new money).
- WARNING: rare — only when a major holding cut its dividend.
Always express both the annualized dividend amount in the user's currency AND the weighted yield as a percentage of the dividend-paying stock allocation. Skip this lens for portfolios with zero dividend-paying holdings.`,
};
